name = "Liga"
uuid = "c6f2b8c2-80b4-11e9-198e-97a7f734ea2b"
authors = ["evcastelani <emersonvitor@gmail.com>", "J. Silva <jairmt@gmail.com>","W. Shirabayashi <wvishirabayashi@uem.br>","V. Riter <viniriter@gmail.com >","V.Soares <valtersoaresdecamargo@gmail.com >" ]
version = "0.7.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Documenter = "~0.22"
